"""Generates the bundled style packs (engine/styles/src/commonMain/composeResources/files/styles).

    python3 tools/styles/make_packs.py engine/styles/src/commonMain/composeResources/files/styles

Each pack is pure data (docs/STYLE_PACKS.md). Preview any pack with
`./gradlew :engine:styles:stylePreview -Ppack=<file>`.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
import shaders as S  # noqa: E402
from shaders_and_launch import packs as LAUNCH  # noqa: E402


def pack(pid, fa, en, dfa, den, family, cost, tags, palette, captions, background, overlay=None, elements=None,
         motion=None, sfx=None, audio_only=None, shaders=None):
    spec = {
        "id": pid, "family": family,
        "palette": palette,
        "captions": {
            "mode": "BuildUp", "size": 0.1, "weight": 800, "uppercase": False, "letterSpacingEm": -0.01,
            "maxWordsPerLine": 4, "anchor": "BottomCenter", "entry": "pop", "exit": "fade", "box": "None",
            "strokeWidth": 0.0, "shadowBlur": 0.012,
            "emphasis": {"scale": 1.18, "colorRole": "accent", "box": "None", "threshold": 0.6},
            **{k: v for k, v in captions.items() if k != "emphasis"},
        },
        "background": {"audioReactive": True, **background},
        "overlay": {"grain": 0.02, "vignette": 0.3, "letterbox": 0.0, **(overlay or {})},
        "elements": {"card": "glass", "cornerRadius": 0.04, **(elements or {})},
        "motion": {"energy": 0.6, "cameraPunch": True, **(motion or {})},
        "sfx": sfx or {"caption.emphasis": "sfx/pop", "element.enter": "sfx/whoosh-soft"},
        "audioOnly": {"captionAnchor": "Center", "captionScale": 1.25, "visualizer": "ring", **(audio_only or {})},
    }
    if "emphasis" in captions:
        spec["captions"]["emphasis"].update(captions["emphasis"])
    if shaders:
        spec["shaders"] = shaders
    return pid, {
        "schema": 1, "id": pid, "version": "1.0.0",
        "nameFa": fa, "nameEn": en, "descriptionFa": dfa, "descriptionEn": den,
        "family": family, "cost": cost, "tags": tags, "spec": spec,
    }


def pal(bg, text, accent, accent2, emphasis_text=None, shadow="#00000099"):
    return {"background": bg, "text": text, "accent": accent, "accent2": accent2,
            "emphasisText": emphasis_text or text, "shadow": shadow}


NEW = dict([
    pack("skeuomorphism", "اسکیومورفیسم", "Skeuomorphism",
         "بافت‌های واقعی کاغذ و چرم، سایه‌های نرم و حس اشیای ملموس.",
         "Real-world textures, soft cast shadows and objects you could touch.",
         "TextureCollage", "Medium",
         ["classic", "warm", "craft", "story", "کلاسیک", "گرم", "دست‌ساز", "روایت"],
         pal(["#E9DCC4", "#D2BE98", "#8B5E3C", "#2F5D50"], "#2B2118", "#8B3A2B", "#2F5D50", shadow="#00000055"),
         {"mode": "Phrase", "size": 0.085, "weight": 800, "box": "Pill", "boxColor": "#FFF8EC", "entry": "rise",
          "maxWordsPerLine": 3, "shadowBlur": 0.02, "emphasis": {"scale": 1.12, "colorRole": "accent"}},
         {"preset": "shader:paper"}, {"grain": 0.04, "vignette": 0.45},
         {"card": "solid", "cornerRadius": 0.02}, {"energy": 0.45},
         {"caption.emphasis": "sfx/click", "element.enter": "sfx/swoosh"},
         {"visualizer": "bars"}, {"paper": S.PAPER}),

    pack("neomorphism", "نئومورفیسم", "Neomorphism",
         "سطح مات یکپارچه با برجستگی‌ها و فرورفتگی‌های نرم؛ آرام و مینیمال.",
         "One matte surface with soft extruded and debossed shapes: calm and minimal.",
         "ShaderFx", "Light",
         ["soft", "calm", "minimal", "app", "نرم", "آرام", "مینیمال", "اپلیکیشن"],
         pal(["#E4E9F2", "#FFFFFF", "#A3B1C6", "#6C63FF"], "#2D3142", "#6C63FF", "#FF7A90", shadow="#00000022"),
         {"mode": "BuildUp", "size": 0.088, "weight": 700, "entry": "fade", "shadowBlur": 0.006,
          "emphasis": {"scale": 1.1, "colorRole": "accent"}},
         {"preset": "shader:neumorph"}, {"grain": 0.0, "vignette": 0.08},
         {"card": "solid", "cornerRadius": 0.06}, {"energy": 0.35, "cameraPunch": False},
         {"caption.emphasis": "sfx/tick", "element.enter": "sfx/whoosh-soft"},
         {"visualizer": "bars", "captionScale": 1.15}, {"neumorph": S.NEUMORPH}),

    pack("glassmorphism", "گلس‌مورفیسم", "Glassmorphism",
         "کارت‌های شیشهٔ مات روی گرادیان‌های رنگی؛ مدرن و تمیز.",
         "Frosted glass cards over colourful gradients: modern and clean.",
         "ShaderFx", "Medium",
         ["modern", "clean", "tech", "app", "startup", "مدرن", "تمیز", "تکنولوژی", "استارتاپ"],
         pal(["#1A1446", "#6A3DE8", "#00C2FF", "#FF5FA2"], "#FFFFFF", "#7CF8FF", "#FF8BD0"),
         {"mode": "BuildUp", "size": 0.095, "box": "Glass", "entry": "rise",
          "emphasis": {"scale": 1.18, "colorRole": "accent"}},
         {"preset": "mesh"}, {"grain": 0.02, "vignette": 0.25},
         {"card": "glass", "cornerRadius": 0.05}, {"energy": 0.55},
         {"caption.emphasis": "sfx/shimmer", "element.enter": "sfx/whoosh-soft"}),

    pack("claymorphism", "کلی‌مورفیسم", "Claymorphism",
         "شکل‌های گرد و پف‌دار خمیری با سایه‌های نرم؛ شاد و صمیمی.",
         "Puffy clay-like shapes with soft shading: cheerful and friendly.",
         "ThreeD", "Heavy",
         ["playful", "friendly", "kids", "education", "cute", "شاد", "صمیمی", "کودک", "آموزشی", "بامزه"],
         pal(["#FFE8D6", "#FF9F7A", "#B5EAD7", "#FFD166"], "#3D2C5C", "#FF6F59", "#2EC4B6", "#FFFFFF"),
         {"mode": "Phrase", "size": 0.09, "weight": 900, "box": "Pill", "boxColor": "#FFFFFFE6", "entry": "pop",
          "maxWordsPerLine": 3, "emphasis": {"scale": 1.16, "colorRole": "accent", "box": "Highlight"}},
         {"preset": "shader:clay"}, {"grain": 0.0, "vignette": 0.1},
         {"card": "solid", "cornerRadius": 0.07}, {"energy": 0.65},
         {"caption.emphasis": "sfx/pop", "element.enter": "sfx/pop"},
         {"visualizer": "none", "captionScale": 1.2}, {"clay": S.CLAY}),

    pack("minimalism", "مینیمالیسم", "Minimalism",
         "سفید، فضای خالی و تایپوگرافی دقیق؛ هیچ چیز اضافه‌ای.",
         "White space and precise type, nothing extra.",
         "Vector2D", "Light",
         ["minimal", "clean", "luxury", "corporate", "elegant", "مینیمال", "تمیز", "لوکس", "رسمی", "شیک"],
         pal(["#FAFAF7", "#EDEDE8", "#111111", "#C9A227"], "#111111", "#111111", "#C9A227", shadow="#00000000"),
         {"mode": "Phrase", "size": 0.075, "weight": 600, "letterSpacingEm": 0.0, "entry": "fade", "shadowBlur": 0.0,
          "maxWordsPerLine": 4, "emphasis": {"scale": 1.0, "colorRole": "accent2"}},
         {"preset": "solid", "audioReactive": False}, {"grain": 0.0, "vignette": 0.0},
         {"card": "outline", "cornerRadius": 0.0}, {"energy": 0.25, "cameraPunch": False},
         {"element.enter": "sfx/tick"},
         {"visualizer": "none", "captionScale": 1.1}),

    pack("maximalism", "مکسیمالیسم", "Maximalism",
         "رنگ، الگو و انرژی تا آخرین حد؛ هیچ چیز کم نیست.",
         "Colour, pattern and energy turned all the way up.",
         "Vector2D", "Medium",
         ["bold", "loud", "fashion", "party", "hype", "جسور", "پرسروصدا", "مد", "مهمانی", "هیجانی"],
         pal(["#12002E", "#FF2E97", "#FFC300", "#00E5FF"], "#FFFFFF", "#FFC300", "#00E5FF", "#12002E"),
         {"mode": "SingleWord", "size": 0.12, "weight": 900, "uppercase": True, "entry": "slam", "exit": "shrink",
          "maxWordsPerLine": 1, "anchor": "Center", "strokeWidth": 0.006, "strokeColor": "#12002E",
          "emphasis": {"scale": 1.3, "colorRole": "accent", "box": "Highlight"}},
         {"preset": "shader:kaleido"}, {"grain": 0.03, "vignette": 0.4},
         {"card": "brutal", "cornerRadius": 0.02}, {"energy": 0.95},
         {"caption.emphasis": "sfx/impact", "caption.word": "sfx/tick", "element.enter": "sfx/glitch"},
         {"visualizer": "none", "captionScale": 1.0}, {"kaleido": S.KALEIDO}),

    pack("brutalism", "بروتالیسم", "Brutalism",
         "خام، سیاه‌وسفید و بی‌پرده؛ تایپ درشت روی سطح تخت.",
         "Raw, black and white and unapologetic: huge type on flat ground.",
         "Vector2D", "Light",
         ["raw", "bold", "editorial", "statement", "خام", "جسور", "سرمقاله", "بیانیه"],
         pal(["#F2F2F2", "#000000", "#FF3B00", "#000000"], "#000000", "#FF3B00", "#000000", "#F2F2F2", "#00000000"),
         {"mode": "Phrase", "size": 0.1, "weight": 900, "uppercase": True, "letterSpacingEm": -0.04, "box": "None",
          "entry": "wipe", "shadowBlur": 0.0, "maxWordsPerLine": 2,
          "emphasis": {"scale": 1.0, "colorRole": "accent", "box": "Highlight"}},
         {"preset": "solid", "audioReactive": False}, {"grain": 0.0, "vignette": 0.0},
         {"card": "outline", "cornerRadius": 0.0}, {"energy": 0.7},
         {"caption.emphasis": "sfx/click", "element.enter": "sfx/click"},
         {"visualizer": "bars", "captionScale": 1.15}),

    pack("bento-grid", "بنتو گرید", "Bento Grid",
         "داده‌ها در کاشی‌های مرتب مثل ارائه‌های اپل؛ عالی برای آمار و آموزش.",
         "Information in tidy tiles like a keynote: great for stats and explainers.",
         "Vector2D", "Light",
         ["tech", "data", "explainer", "keynote", "finance", "تکنولوژی", "داده", "توضیحی", "ارائه", "مالی"],
         pal(["#0B0B0F", "#23232E", "#5E5CE6", "#30D158"], "#F5F5F7", "#64D2FF", "#30D158"),
         {"mode": "BuildUp", "size": 0.088, "weight": 800, "box": "Pill", "boxColor": "#1C1C24E6", "entry": "rise",
          "emphasis": {"scale": 1.12, "colorRole": "accent"}},
         {"preset": "grid"}, {"grain": 0.0, "vignette": 0.2},
         {"card": "solid", "cornerRadius": 0.05}, {"energy": 0.5},
         {"caption.emphasis": "sfx/tick", "element.enter": "sfx/swoosh"},
         {"visualizer": "bars"}),

    pack("spatial-ui", "اسپیشال یوآی", "Spatial UI",
         "پنل‌های شناور در عمق و نور نرم اتاق؛ حس واقعیت ترکیبی.",
         "Panels floating at depth in a softly lit room: a mixed-reality feel.",
         "ThreeD", "Heavy",
         ["futuristic", "tech", "premium", "vision", "آینده‌نگر", "تکنولوژی", "لوکس", "فضایی"],
         pal(["#1B1F2A", "#3A4258", "#A8B5D9", "#FFFFFF"], "#FFFFFF", "#9FD8FF", "#FFD6A5"),
         {"mode": "BuildUp", "size": 0.09, "weight": 700, "box": "Glass", "entry": "rise",
          "emphasis": {"scale": 1.12, "colorRole": "accent"}},
         {"preset": "shader:spatial"}, {"grain": 0.015, "vignette": 0.35},
         {"card": "glass", "cornerRadius": 0.06}, {"energy": 0.45},
         {"caption.emphasis": "sfx/shimmer", "element.enter": "sfx/whoosh-soft"},
         {"visualizer": "ring"}, {"spatial": S.SPATIAL}),

    pack("aurora-ui", "آئورورا یوآی", "Aurora UI",
         "پرده‌های نور شفق که با صدای تو تنفس می‌کنند؛ رؤیایی و آرام.",
         "Curtains of aurora light that breathe with your voice: dreamy and calm.",
         "ShaderFx", "Medium",
         ["dreamy", "calm", "meditation", "music", "podcast", "رؤیایی", "آرام", "مدیتیشن", "موسیقی", "پادکست"],
         pal(["#030712", "#0F5257", "#3D2C8D", "#C147E9"], "#F4F7FF", "#7DF9C4", "#E3A4FF"),
         {"mode": "Karaoke", "size": 0.09, "weight": 700, "entry": "fade", "maxWordsPerLine": 4,
          "emphasis": {"scale": 1.1, "colorRole": "accent"}},
         {"preset": "aurora"}, {"grain": 0.03, "vignette": 0.4},
         {"card": "glass", "cornerRadius": 0.05}, {"energy": 0.4, "cameraPunch": False},
         {"caption.emphasis": "sfx/shimmer", "element.enter": "sfx/whoosh-soft"},
         {"visualizer": "ring", "captionScale": 1.2}),

    pack("retrofuturism", "رترو فیوچریسم", "Retrofuturism",
         "غروب سینت‌ویو، خورشید راه‌راه و شبکهٔ نئون تا افق.",
         "Synthwave dusk, a striped sun and a neon grid to the horizon.",
         "TextureCollage", "Medium",
         ["retro", "80s", "neon", "music", "gaming", "رترو", "دهه۸۰", "نئون", "موسیقی", "گیمینگ"],
         pal(["#120024", "#FF2A6D", "#FFB86C", "#2A0845"], "#FFFFFF", "#05D9E8", "#FF2A6D", "#120024"),
         {"mode": "Phrase", "size": 0.092, "weight": 900, "uppercase": True, "entry": "wipe", "maxWordsPerLine": 3,
          "strokeWidth": 0.004, "strokeColor": "#120024", "emphasis": {"scale": 1.15, "colorRole": "accent"}},
         {"preset": "shader:synthwave"}, {"grain": 0.035, "vignette": 0.45, "letterbox": 0.06},
         {"card": "outline", "cornerRadius": 0.01}, {"energy": 0.75},
         {"caption.emphasis": "sfx/riser", "element.enter": "sfx/swoosh"},
         {"visualizer": "bars", "captionAnchor": "TopCenter"}, {"synthwave": S.SYNTHWAVE}),

    pack("y2k", "وای‌توکی", "Y2K",
         "کروم براق، حباب‌های رنگین‌کمانی و حس اینترنت دهه ۲۰۰۰.",
         "Glossy chrome, iridescent bubbles and early-2000s internet energy.",
         "TextureCollage", "Medium",
         ["y2k", "fashion", "pop", "nostalgia", "gen-z", "مد", "پاپ", "نوستالژی", "جوان"],
         pal(["#E8E6FF", "#B8F2FF", "#FFC2F1", "#7B61FF"], "#1E1440", "#7B61FF", "#FF4FB8", "#FFFFFF"),
         {"mode": "BuildUp", "size": 0.095, "weight": 900, "box": "Pill", "boxColor": "#FFFFFFCC", "entry": "flip",
          "emphasis": {"scale": 1.18, "colorRole": "accent", "box": "Highlight"}},
         {"preset": "shader:iridescent"}, {"grain": 0.015, "vignette": 0.15},
         {"card": "glass", "cornerRadius": 0.08}, {"energy": 0.7},
         {"caption.emphasis": "sfx/ding", "element.enter": "sfx/pop"},
         {"visualizer": "ring"}, {"iridescent": S.IRIDESCENT}),

    pack("chrome-liquid-metal", "کروم / لیکوئید متال", "Chrome / Liquid Metal",
         "فلز مایع درخشان با بازتاب‌های تیز استودیو؛ لوکس و قدرتمند.",
         "Glossy liquid metal with sharp studio reflections: luxurious and powerful.",
         "ShaderFx", "Heavy",
         ["luxury", "premium", "tech", "car", "crypto", "لوکس", "قدرتمند", "تکنولوژی", "ماشین", "کریپتو"],
         pal(["#07080B", "#3A404C", "#DDE3EE", "#9FB8FF"], "#FFFFFF", "#C7D3FF", "#FFD27A", "#0B0C10"),
         {"mode": "SingleWord", "size": 0.11, "weight": 900, "uppercase": True, "anchor": "Center", "entry": "slam",
          "exit": "shrink", "maxWordsPerLine": 1, "shadowBlur": 0.03,
          "emphasis": {"scale": 1.25, "colorRole": "accent2"}},
         {"preset": "shader:chrome"}, {"grain": 0.02, "vignette": 0.5},
         {"card": "glass", "cornerRadius": 0.03}, {"energy": 0.8},
         {"caption.emphasis": "sfx/impact", "element.enter": "sfx/whoosh"},
         {"visualizer": "none", "captionScale": 1.0}, {"chrome": S.CHROME}),

    pack("dark-mode-ui", "دارک مود یوآی", "Dark Mode UI",
         "تاریک و آرام برای چشم، با یک رنگ تأکیدی روشن؛ مثل اپ‌های حرفه‌ای.",
         "Dark and easy on the eyes with one bright accent, like pro apps.",
         "Vector2D", "Light",
         ["dark", "pro", "tech", "coding", "finance", "تاریک", "حرفه‌ای", "برنامه‌نویسی", "مالی"],
         pal(["#0D1117", "#161B22", "#2F81F7", "#3FB950"], "#E6EDF3", "#2F81F7", "#3FB950"),
         {"mode": "BuildUp", "size": 0.088, "weight": 700, "box": "Pill", "boxColor": "#161B22F2", "entry": "rise",
          "emphasis": {"scale": 1.1, "colorRole": "accent"}},
         {"preset": "gradient", "audioReactive": False}, {"grain": 0.0, "vignette": 0.25},
         {"card": "solid", "cornerRadius": 0.03}, {"energy": 0.5},
         {"caption.emphasis": "sfx/tick", "element.enter": "sfx/swoosh"},
         {"visualizer": "bars"}),

    pack("flat-design", "فلت دیزاین", "Flat Design",
         "رنگ‌های تخت و شاد، بدون سایه و گرادیان؛ ساده و خوانا.",
         "Bright flat colours, no shadows or gradients: simple and legible.",
         "Vector2D", "Light",
         ["simple", "friendly", "explainer", "education", "ساده", "صمیمی", "توضیحی", "آموزشی"],
         pal(["#2EC4B6", "#CBF3F0", "#FF9F1C", "#E71D36"], "#FFFFFF", "#FFBF69", "#E71D36", "#011627", "#00000000"),
         {"mode": "Phrase", "size": 0.09, "weight": 900, "box": "Pill", "boxColor": "#011627", "entry": "pop",
          "shadowBlur": 0.0, "maxWordsPerLine": 3, "emphasis": {"scale": 1.12, "colorRole": "accent"}},
         {"preset": "solid", "audioReactive": False}, {"grain": 0.0, "vignette": 0.0},
         {"card": "solid", "cornerRadius": 0.03}, {"energy": 0.6},
         {"caption.emphasis": "sfx/pop", "element.enter": "sfx/pop"},
         {"visualizer": "bars"}),

    pack("material-design", "متریال دیزاین", "Material Design",
         "زبان طراحی گوگل: رنگ‌های بیانی، گوشه‌های گرد و حرکت فنری.",
         "Google's Material: expressive colour, rounded shapes, springy motion.",
         "Vector2D", "Light",
         ["android", "app", "tech", "tutorial", "اندروید", "اپلیکیشن", "تکنولوژی", "آموزشی"],
         pal(["#1C1B1F", "#381E72", "#D0BCFF", "#EFB8C8"], "#E6E1E5", "#D0BCFF", "#EFB8C8", "#381E72"),
         {"mode": "BuildUp", "size": 0.09, "weight": 800, "box": "Pill", "boxColor": "#2B2930F2", "entry": "pop",
          "emphasis": {"scale": 1.14, "colorRole": "accent", "box": "Highlight"}},
         {"preset": "mesh"}, {"grain": 0.0, "vignette": 0.2},
         {"card": "solid", "cornerRadius": 0.07}, {"energy": 0.6},
         {"caption.emphasis": "sfx/pop", "element.enter": "sfx/swoosh"}),

    pack("anti-design", "آنتی‌دیزاین", "Anti-Design",
         "قوانین شکسته، رنگ‌های متضاد و بی‌نظمی عمدی؛ جسورانه و غیرمنتظره.",
         "Rules broken on purpose: clashing colour and deliberate chaos.",
         "Vector2D", "Light",
         ["experimental", "art", "underground", "music", "تجربی", "هنری", "زیرزمینی", "موسیقی"],
         pal(["#00FF41", "#FF00E6", "#FFFF00", "#0000FF"], "#000000", "#0000FF", "#FF00E6", "#FFFF00", "#00000000"),
         {"mode": "SingleWord", "size": 0.12, "weight": 900, "uppercase": True, "anchor": "Center", "entry": "flip",
          "exit": "fall", "maxWordsPerLine": 1, "box": "Brutal", "boxColor": "#FFFFFF", "shadowBlur": 0.0,
          "letterSpacingEm": 0.02, "emphasis": {"scale": 1.35, "colorRole": "accent2"}},
         {"preset": "shader:chaos"}, {"grain": 0.05, "vignette": 0.0},
         {"card": "brutal", "cornerRadius": 0.0}, {"energy": 1.0},
         {"caption.emphasis": "sfx/glitch", "caption.word": "sfx/click", "element.enter": "sfx/glitch"},
         {"visualizer": "none", "captionScale": 1.0}, {"chaos": S.CHAOS}),

    pack("grain-noise", "گرین و نویز", "Grain & Noise",
         "گرادیان‌های غنی زیر دانهٔ فیلم درشت؛ گرم، هنری و سینمایی.",
         "Rich gradients under heavy film grain: warm, artful and cinematic.",
         "ShaderFx", "Medium",
         ["cinematic", "art", "film", "story", "fashion", "سینمایی", "هنری", "فیلم", "روایت", "مد"],
         pal(["#140D0B", "#C8553D", "#2D3047", "#F28F3B"], "#FFF4E6", "#F6C177", "#EB6F92"),
         {"mode": "Phrase", "size": 0.088, "weight": 700, "entry": "fade", "maxWordsPerLine": 4,
          "emphasis": {"scale": 1.08, "colorRole": "accent"}},
         {"preset": "shader:grain"}, {"grain": 0.06, "vignette": 0.5, "letterbox": 0.08},
         {"card": "outline", "cornerRadius": 0.01}, {"energy": 0.4, "cameraPunch": False},
         {"caption.emphasis": "sfx/whoosh-soft", "element.enter": "sfx/whoosh-soft"},
         {"visualizer": "ring"}, {"grain": S.GRAIN_GRADIENT}),

    pack("scrapbook", "اسکرپ‌بوک", "Scrapbook UI",
         "کاغذ پاره، نوارچسب و برچسب‌های دست‌ساز؛ شخصی و نوستالژیک.",
         "Torn paper, tape and handmade labels: personal and nostalgic.",
         "TextureCollage", "Medium",
         ["personal", "vlog", "travel", "memory", "craft", "شخصی", "ولاگ", "سفر", "خاطره", "دست‌ساز"],
         pal(["#F3E9DC", "#E6CCB2", "#9C6644", "#7F9C96"], "#2B2118", "#D1495B", "#00798C", "#FFFFFF", "#00000044"),
         {"mode": "Phrase", "size": 0.088, "weight": 800, "box": "Brutal", "boxColor": "#FFFDF7", "entry": "flip",
          "maxWordsPerLine": 3, "shadowBlur": 0.0, "emphasis": {"scale": 1.1, "colorRole": "accent", "box": "Highlight"}},
         {"preset": "shader:scrap"}, {"grain": 0.045, "vignette": 0.35},
         {"card": "solid", "cornerRadius": 0.01}, {"energy": 0.55},
         {"caption.emphasis": "sfx/click", "element.enter": "sfx/swoosh"},
         {"visualizer": "none"}, {"scrap": S.PAPER}),

    pack("sticker-ui", "استیکر یوآی", "Sticker UI",
         "استیکرهای براق با حاشیهٔ سفید و کانفتی؛ شاد و قابل‌اشتراک.",
         "Glossy stickers with white borders and confetti: joyful and shareable.",
         "TextureCollage", "Light",
         ["fun", "kids", "party", "social", "cute", "شاد", "کودک", "جشن", "شبکه‌اجتماعی", "بامزه"],
         pal(["#FFF6FB", "#FFD6EC", "#FF5DA2", "#4CC9F0"], "#1D1A39", "#FF5DA2", "#4CC9F0", "#FFFFFF"),
         {"mode": "BuildUp", "size": 0.095, "weight": 900, "box": "Pill", "boxColor": "#FFFFFF", "entry": "pop",
          "strokeWidth": 0.0, "emphasis": {"scale": 1.22, "colorRole": "accent", "box": "Highlight"}},
         {"preset": "shader:confetti"}, {"grain": 0.0, "vignette": 0.0},
         {"card": "brutal", "cornerRadius": 0.06}, {"energy": 0.8},
         {"caption.emphasis": "sfx/pop", "caption.word": "sfx/tick", "element.enter": "sfx/pop"},
         {"visualizer": "none", "captionScale": 1.2}, {"confetti": S.CONFETTI}),

    pack("biophilic-design", "بیوفیلیک دیزاین", "Biophilic Design",
         "سبزهای طبیعی، سایه‌روشن برگ‌ها و نور ملایم؛ آرامش طبیعت.",
         "Natural greens, dappled leaf light and soft daylight: nature's calm.",
         "Organic", "Medium",
         ["nature", "wellness", "health", "calm", "food", "طبیعت", "سلامت", "آرامش", "غذا", "سبز"],
         pal(["#0F2A1D", "#2D6A4F", "#95D5B2", "#F4E285"], "#F1FAEE", "#B7E4C7", "#F4E285"),
         {"mode": "Karaoke", "size": 0.088, "weight": 700, "entry": "rise", "maxWordsPerLine": 4,
          "emphasis": {"scale": 1.08, "colorRole": "accent2"}},
         {"preset": "shader:organic"}, {"grain": 0.025, "vignette": 0.35},
         {"card": "glass", "cornerRadius": 0.08}, {"energy": 0.35, "cameraPunch": False},
         {"caption.emphasis": "sfx/whoosh-soft", "element.enter": "sfx/whoosh-soft"},
         {"visualizer": "ring"}, {"organic": S.ORGANIC}),

    pack("3d-immersive", "تری‌دی ایمرسیو", "3D & Immersive",
         "تونل سه‌بعدی بی‌پایان که با صدای تو شتاب می‌گیرد؛ غرق‌کننده.",
         "An endless 3D tunnel that speeds up with your voice: immersive.",
         "ThreeD", "Heavy",
         ["immersive", "gaming", "tech", "music", "hype", "غرق‌کننده", "گیمینگ", "تکنولوژی", "موسیقی", "هیجانی"],
         pal(["#03001C", "#5B2EFF", "#00F5D4", "#F15BB5"], "#FFFFFF", "#00F5D4", "#F15BB5", "#03001C"),
         {"mode": "SingleWord", "size": 0.11, "weight": 900, "uppercase": True, "anchor": "Center", "entry": "slam",
          "exit": "shrink", "maxWordsPerLine": 1, "shadowBlur": 0.03, "emphasis": {"scale": 1.28, "colorRole": "accent"}},
         {"preset": "shader:tunnel"}, {"grain": 0.02, "vignette": 0.55},
         {"card": "glass", "cornerRadius": 0.03}, {"energy": 0.9},
         {"caption.emphasis": "sfx/impact", "element.enter": "sfx/riser"},
         {"visualizer": "none", "captionScale": 1.0}, {"tunnel": S.TUNNEL}),

    pack("motion-driven-ui", "موشن‌دریون یوآی", "Motion-Driven UI",
         "همه‌چیز در حرکت: موج‌های صوتی، ورودهای سریع و ریتم دقیق.",
         "Everything moves: audio waves, quick entrances and tight rhythm.",
         "Vector2D", "Light",
         ["dynamic", "music", "podcast", "fast", "پویا", "موسیقی", "پادکست", "سریع"],
         pal(["#0A0F1F", "#1F6FEB", "#00D4FF", "#FF6B9D"], "#FFFFFF", "#00D4FF", "#FF6B9D"),
         {"mode": "BuildUp", "size": 0.095, "weight": 900, "entry": "wipe", "exit": "fall",
          "emphasis": {"scale": 1.2, "colorRole": "accent"}},
         {"preset": "waves"}, {"grain": 0.015, "vignette": 0.3},
         {"card": "glass", "cornerRadius": 0.04}, {"energy": 0.85},
         {"caption.emphasis": "sfx/swoosh", "caption.word": "sfx/tick", "element.enter": "sfx/whoosh"},
         {"visualizer": "bars"}),

    pack("experimental-typography", "اکسپریمنتال تایپوگرافی", "Experimental Typography",
         "تایپ به‌عنوان هنر: باندهای پاره، گلیچ و چیدمان غیرعادی.",
         "Type as art: torn scan bands, glitches and unusual layouts.",
         "Typography", "Medium",
         ["art", "experimental", "music", "fashion", "edgy", "هنری", "تجربی", "موسیقی", "مد", "جسور"],
         pal(["#0A0A0A", "#F5F5F5", "#FF003C", "#00F0FF"], "#F5F5F5", "#FF003C", "#00F0FF", "#0A0A0A"),
         {"mode": "SingleWord", "size": 0.13, "weight": 900, "uppercase": True, "anchor": "Center", "entry": "flip",
          "exit": "fall", "maxWordsPerLine": 1, "letterSpacingEm": 0.04, "shadowBlur": 0.0,
          "emphasis": {"scale": 1.3, "colorRole": "accent", "box": "Highlight"}},
         {"preset": "shader:glitch"}, {"grain": 0.05, "vignette": 0.3},
         {"card": "outline", "cornerRadius": 0.0}, {"energy": 0.9},
         {"caption.emphasis": "sfx/glitch", "caption.word": "sfx/click", "element.enter": "sfx/glitch"},
         {"visualizer": "none", "captionScale": 1.0}, {"glitch": S.GLITCH}),

    pack("organic-ui", "اورگانیک یوآی", "Organic UI",
         "شکل‌های نرم و جاری با رنگ‌های خاکی؛ انسانی و گرم.",
         "Soft flowing forms in earthy colours: human and warm.",
         "Organic", "Medium",
         ["warm", "human", "wellness", "lifestyle", "beauty", "گرم", "انسانی", "سلامت", "سبک‌زندگی", "زیبایی"],
         pal(["#F2E8DF", "#E3B5A4", "#B5838D", "#6D6875"], "#3A2E39", "#B5525C", "#6D6875", "#FFFFFF", "#00000033"),
         {"mode": "Phrase", "size": 0.088, "weight": 700, "box": "Pill", "boxColor": "#FFFFFFB3", "entry": "rise",
          "maxWordsPerLine": 3, "emphasis": {"scale": 1.1, "colorRole": "accent"}},
         {"preset": "shader:flow"}, {"grain": 0.02, "vignette": 0.15},
         {"card": "solid", "cornerRadius": 0.09}, {"energy": 0.4, "cameraPunch": False},
         {"caption.emphasis": "sfx/whoosh-soft", "element.enter": "sfx/whoosh-soft"},
         {"visualizer": "ring"}, {"flow": S.ORGANIC}),
])

ALL = {**LAUNCH, **NEW}

if __name__ == "__main__":
    out = sys.argv[1]
    for pid, p in ALL.items():
        with open(os.path.join(out, f"{pid}.json"), "w", encoding="utf-8") as f:
            json.dump(p, f, ensure_ascii=False, indent=2)
            f.write("\n")
    print(len(ALL), "packs written")
